export const HANDLE_TAG_TITLE = "HANDLE_TAG_TITLE";
export const SET_TAG_DEFAULTS = "SET_TAG_DEFAULTS";

export const LIST_TAGS = "LIST_TAGS";
export const LIST_TAGS_SUCCESS = "LIST_TAG_SUCCESS";
export const LIST_TAGS_FAILURE = "LIST_TAG_FAILURE";

export const DELETE_TAGS = "DELETE_TAGS";
export const DELETE_TAGS_SUCCESS = "DELETE_TAGS_SUCCESS";
export const DELETE_TAGS_FAILURE = "DELETE_TAGS_FAILURE";

export const EDIT_TAGS = "EDIT_TAGS";
export const EDIT_TAGS_SUCCESS = "EDIT_TAGS_SUCCESS";
export const EDIT_TAGS_FAILURE = "EDIT_TAGS_FAILURE";

export const SHOW_TAGS = "SHOW_TAGS";
export const SHOW_TAGS_SUCCESS = "SHOW_TAGS_SUCCESS";
export const SHOW_TAGS_FAILURE = "SHOW_TAGS_FAILURE";

export const CREATE_TAGS = "CREATE_TAGS";
export const CREATE_TAGS_SUCCESS = "CREATE_TAGS_SUCCESS";
export const CREATE_TAGS_FAILURE = "CREATE_TAGS_FAILURE";

export const LIST_ALL_TAGS = 'LIST_ALL_TAGS';